### ISSUE TITLE
Rewrite the story

### ISSUE THREAD

**Issue by thepaperpilot** [thepaperpilot/12-is-strange#1]
Now that the game jam is over, development can relax and take a more leisurely pace to flesh things out and do things right, not fast. With that in mind, I think the first thing that needs to be done is a rewrite of the story and puzzles. But before even that, the direction of the game needs to be ascertained. Taking story and puzzles from life is strange was alright when it was for a jam and we didn't have time for original stories, but now that's not a restriction. So I think we should work on diverging our plot and puzzles from that of life is strange. 

I currently have two ideas for directions we can go instead:
1.  12 different areas, 12 hours each. Give player full control of when/where they are. Events in each area/time combo affect the others. I like the idea of this open world kind of story, and it would allow us to add puzzle requirements anywhere in the game world, since they're always accessible. But, I feel it'll be hard to make a cohesive story around this idea, since the player can go anywhere at any time, and a lot of story-driven events would have to be made mandatory, or else realistically be ignored. 
2. Limit the player's control over time. Sometimes they won't be able to go as far back as they thought they could. Sometimes they jump forward unexpectedly. With the developers in control, story can take precedent, and puzzles will be easier since they'll be more localized. This is more similar to the way Life is Strange does it, but I feel the defining difference would be the focus of the story. LiS focuses on the tornado, and deliberately doesn't make any steps towards explaining the powers. Our game could have an original story that _does_ focus on the powers, and center all conflicts around that. 

To be clear, I'm not a great writer, and what you saw here were not story ideas. They were ideas for how the game would flow. Personally I'm leaning more towards the second. While the story is being written (by someone else, mainly. I can assist, but absolutely not do it all), I could work on the engine, adding things like a dialogue system.

**Comment by thepaperpilot** [comment]
Also, I feel idea #2 would stray from the "12" theme, so I think it would warrant a new name. I could put a "gamejam version" download on the itch page compiled from the current source, and replace the version that plays in the browser with the game in its new state.

**Comment by dsleaz** [comment]
The first version should be bug free with the one ending.

Version 2 should be separate.

Sent from my Verizon 4G LTE Smartphone

---- The Paper Pilot wrote ----

**Comment by thepaperpilot** [comment]
I've had some more thoughts, that I'm just going to put here. I am willing to discuss and change anything, within reason.

We base the time travel mechanic after H.G.Wells' idea book "the time machine". Basically, time is a 4th dimension where any moment in time is a 3rd dimensional slice, and everyone has a constant velocity through which they travel along this 4th axis. The player will have a device, I'm thinking a necklace with a clock on it, that allows them to change their relative velocity compared to everything else, effectively travelling through time. I have an idea for a nice animation, where basically while travelling the world fades out to reveal the purple particle effect I made, representing the time stream, and then fades back in when we stop travelling.

The player would have full access to all 12 hours, in a variety of scenes, like idea 1 in the original post. But, this would just be one "level". After solving each level, you'd go to the next, which would take place in a different 12 hour period. Players can NOT travel between periods at will, akin to idea #2. Also, each period can have different areas, and different numbers of areas, so we don't have to have a ton of very complex 12 area puzzles, but we could. Also, these areas can be different sizes. I can move the cameras however I want, so for areas like the office and dorm, instead of having parts of the area be blocked off and gradiented, I could just make the camera focus on the area that matters. 

I think this is a nice way to set things up that takes the best parts from idea 1 and 2, and will do a lot in separating our game from LiS.

**Comment by thepaperpilot** [comment]
@dsleaz make a fork. You'll be able to cherry pick the bug fix commits from here, and I can submit a PR to your fork with an ending. Then you'll get your version without requiring a new repository or store page

**Comment by thepaperpilot** [comment]
New story outline added in 24dd8f95efb97f89184eefad5776a497ce44c684
